# Yarn Berry (v4) configuration
nodeLinker: node-modules

# Hoist all dependencies to root (no nested node_modules in packages/frontend or packages/backend)
nmHoistingLimits: none

# Enable global cache (helps with permission issues)
enableGlobalCache: true
