# Yarn Berry (v4) configuration
nodeLinker: node-modules

# Keep dependencies in each workspace's own node_modules
nmHoistingLimits: workspaces

# Enable global cache (helps with permission issues)
enableGlobalCache: true
